on:
  schedule:
    - cron:  '0 4 ? * SUN'
  workflow_dispatch:

name: Generate Release

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: greyltc/archlinux-aur
      options: -v /__w/model-webviewer-ci/model-webviewer-ci:/volume_mount:rw
      #options: -v package_dir:/volume_mount:rw
      #volumes: 
      #  - /package_dir:/volume_mount
    steps:
      - name: Build in docker
        run: |
          sed -i "s,^PKGEXT=.*,PKGEXT='.pkg.tar.zst',g" /etc/makepkg.conf
          sudo -u aurbuilder -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm aurvote'
          cp /var/aurbuilder/.cache/yay/aurvote/*.pkg.tar.zst /github/home
          cp /var/aurbuilder/.cache/yay/aurvote/*.pkg.tar.zst /github/workflow
          cp /var/aurbuilder/.cache/yay/aurvote/*.pkg.tar.zst /volume_mount
          cp /var/aurbuilder/.cache/yay/aurvote/*.pkg.tar.zst /__w/_actions
          cp /var/aurbuilder/.cache/yay/aurvote/*.pkg.tar.zst /__w/_temp
          cp /var/aurbuilder/.cache/yay/aurvote/*.pkg.tar.zst /__w
          ls -al /volume_mount
          ls -al /github/workflow
          ls -al /github/home
      - shell: bash
        run: |
          uname -a
          mount
          pwd
          ls -al
          ls -al /__w/model-webviewer-ci/model-webviewer-ci
          ls -al /home/runner/work
          ls -al /home/runner/work/_temp
          ls -al /home/runner/work/_actions
          ls -al /home/runner/work/_temp/_github_home
          ls -al /home/runner/work/_temp/_github_workflow
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pakage
          path: /home/runner/work
  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${{ env.TODAY }}.0.${{ github.run_number }}
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: package
      - shell: bash
        run: |
          ls -al
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.TODAY }}.0.${{ github.run_number }}
          release_name: Release ${{ env.TODAY }}.0.${{ github.run_number }}
          draft: false
          prerelease: false
