on:
  schedule:
    - cron:  '0 4 ? * SUN'
  workflow_dispatch:

name: Generate Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: greyltc/archlinux-aur
    steps:
         - run: |
             sed -i "s,^PKGEXT=.*,PKGEXT='.pkg.tar.zst',g" /etc/makepkg.conf
             sudo -u aurbuilder -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm aurvote'
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ env.TODAY }}.0.${{ github.run_number }}
          draft: false
          prerelease: false
