on:
  schedule:
    - cron:  '0 4 ? * SUN'
  workflow_dispatch:

name: Generate Release

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: greyltc/archlinux-aur
    steps:
      - name: Build with Arch in docker
        run: |
          sed -i "s,^PKGEXT=.*,PKGEXT='.pkg.tar.zst',g" /etc/makepkg.conf
          #sudo -u aurbuilder -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm occt-webgl-viewer'
          sudo -u aurbuilder -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm aurvote'
          cp /var/cache/makepkg/pkg/*.pkg.tar.zst ${HOME}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: /github/home/*pkg.tar.zst
  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${{ env.TODAY }}.0.${{ github.run_number }}
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: package
      - shell: bash
        run: |
          sudo apt-get install zstd
          ls -al
          tar -I zstd -xvf *.tar.zst
          #tree
          zip -r usr.zip usr
          #zip -r www.zip opt/occt-webgl-viewer/usr/local/*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.TODAY }}.0.${{ github.run_number }}
          release_name: Release ${{ env.TODAY }}.0.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Attach assets to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.tar.zst;www.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v${{ env.TODAY }}.0.${{ github.run_number }}
